CREATE TABLE CLIENT(
  IDClient NUMBER(5),
  Nom VARCHAR2(20)NOT NULL,
  Prenom VARCHAR2(20) NOT NULL,
  Email VARCHAR2(35) NOT NULL,
  NumTel NUMBER(12),
CONSTRAINT CleClient PRIMARY KEY (IDClient));

CREATE TABLE CARTE(
  IDCarte NUMBER(5),
  Nom VARCHAR2(20),
  Categorie VARCHAR2(20),
  IDClient NUMBER(5)NOT NULL,
CONSTRAINT CleCarte PRIMARY KEY(IDCarte),
CONSTRAINT CirCarte FOREIGN KEY (IDClient) REFERENCES CLIENT);

CREATE TABLE POSITION(
  IDPosition NUMBER(5),
  Longitude NUMBER(11) NOT NULL,
  Latitude NUMBER(11) NOT NULL,
CONSTRAINT ClePosition PRIMARY KEY(IDPosition));

CREATE TABLE POSCARTE(
  IDPosition NUMBER(5),
  IDCarte NUMBER(5),
CONSTRAINT CirPoscarte FOREIGN KEY (IDPosition) REFERENCES POSITION,
CONSTRAINT CirPoscarte2 FOREIGN KEY (IDCarte) REFERENCES CARTE);

CREATE TABLE INFOPOSITION(
  IDInfo NUMBER(5),
  IDPosition NUMBER(5) NOT NULL,
  Type VARCHAR2(20),
  Description VARCHAR2(100),
CONSTRAINT CleInfoPosition PRIMARY KEY (IDInfo),
CONSTRAINT CirInfoPosition FOREIGN KEY (IDPosition) REFERENCES POSITION);



